#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)
host = data.get("host", "")
# Set email
rdb = agent.redis_connect(use_replica=True)
smtp_settings = agent.get_smarthost_settings(rdb)
SMTP_HOST= smtp_settings['host']
SMTP_PORT= smtp_settings['port']
SMTP_USERNAME= smtp_settings['username']
SMTP_PASSWORD= smtp_settings['password']
SMTP_ENCRYPTION= smtp_settings['encrypt_smtp']
SMTP_TLSVERIFY= smtp_settings['tls_verify']

#This is specific to you module, so you need to change it accordingly.

HOST = data.get('host')
NODE_ENV= data.get("NODE_ENV", "production")
AFFINE_ADMIN_EMAIL= data.get("AFFINE_ADMIN_EMAIL", "admin@gmail.com")
AFFINE_ADMIN_PASSWORD= data.get("AFFINE_ADMIN_PASSWORD", "admin1234")
app_config = {
    "NODE_ENV": NODE_ENV,
    "AFFINE_ADMIN_EMAIL": AFFINE_ADMIN_EMAIL,
    "AFFINE_ADMIN_PASSWORD": AFFINE_ADMIN_PASSWORD,
    "NODE_OPTIONS": "--import=./scripts/register.js",
    "MAILER_HOST": SMTP_HOST,
    "MAILER_PORT": SMTP_PORT,
    "MAILER_USER": SMTP_USERNAME,
    "MAILER_SENDER": SMTP_USERNAME,
    "MAILER_SECURE": "true",
    "MAILER_PASSWORD": SMTP_PASSWORD,
    "AFFINE_SERVER_HOST": "https://"+host
}
agent.write_envfile("app.env", app_config)
# just before starting systemd unit
#agent.dump_env()
