#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent
import secrets

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

def generate_random_password():
    return secrets.token_urlsafe(16)

#Postgres DB
POSTGRES_USER= data.get("POSTGRES_USER", "postgres")
POSTGRES_PASSWORD= generate_random_password()
POSTGRES_DB= data.get("POSTGRES_DB", "affine")

db = {
    "POSTGRES_USER": POSTGRES_USER,
    "POSTGRES_PASSWORD": POSTGRES_PASSWORD,
    "POSTGRES_DB": POSTGRES_DB,
}
agent.write_envfile("database.env", db)

REDIS_SERVER_HOST= data.get("REDIS_SERVER_HOST", "redis-app")
POSTGRES_URL = f"postgres://{POSTGRES_USER}:{POSTGRES_PASSWORD}@postgresql-app:5432/{POSTGRES_DB}"
app_config = {
    "REDIS_SERVER_HOST": REDIS_SERVER_HOST,
    "DATABASE_URL": POSTGRES_URL,
}
agent.write_envfile("app-db.env", app_config)
# just before starting systemd unit
#agent.dump_env()
